gitRepoUrl = "https://github.com/xSwezan/SuperGlobal"
gitSourceBranch = "main"

classOrder = [
	"SuperGlobal",
	"Store",
]

[home]
enabled = true
includeReadme = true


[docusaurus]
tagline = "Simplified Global Server Communication"

[[navbar.items]]
href = "https://www.roblox.com/library/11615909686"
label = "Model"
position = "right"

[[home.features]]
title = "Easy To Use"
description = "This Library is Easy To Use with straight a forward API"